### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lalasou** [Waseh/rclone-unraid#17] opened 2022-01-20 14:32 UTC
ping -q -c2 8.8.8.8 >/dev/null || ping -q -c2 1.1.1.1 >/dev/null || ping -q -c2 $rcloneurl >/dev/null

**Comment by Waseh** [comment] 2022-01-20 15:49
This really isn't a very helpful.
What bug do you believe you are experiencing? The above line is working as intended in my testing.

**Comment by lalasou** [comment] 2022-01-20 16:23
ping: https://downloads.rclone.org/rclone-current-linux-amd64.zip: Name or service not known

**Comment by lalasou** [comment] 2022-01-20 16:24
or   ping downloads.rclone.org?

**Comment by Waseh** [comment] 2022-01-20 16:54
You're correct, the ping shouldn't be the full url.
Fixed in [5cb5493](https://github.com/Waseh/rclone-unraid/commit/5cb5493221d4a48c75451857b598e421e9b87599)

**Closed by Waseh** 2022-01-20 16:54 UTC

**Comment by Waseh** [comment] 2022-01-20 18:14
Now with fixes for regression introduced in scripts and settings page

**Comment by lalasou** [comment] 2022-01-21 00:46
OK
